abbr 1="cd ~1"
abbr 2="cd ~2"
abbr 3="cd ~3"
abbr 4="cd ~4"
abbr 5="cd ~5"
abbr 6="cd ~6"
abbr 7="cd ~7"
abbr 8="cd ~8"
abbr 9="cd ~9"
abbr aled="nano ~/.zsh_custom/aliases.zsh"
abbr d="dirs -v | head -10"
abbr dcb="docker compose build"
abbr dcd="docker compose down"
abbr dcdb="docker compose --profile dev build"
abbr dcdd="docker compose --profile dev down"
abbr dcdu="docker compose --profile dev up -d"
abbr dcls="docker container ls"
abbr dcp="docker container prune"
abbr dcrb="docker compose down && docker compose build && docker compose up -d"
abbr dcu="docker compose up -d"
abbr de="docker exec -it"
abbr dils="docker image ls"
abbr dip="docker image prune -a"
abbr dl="cd ~/Downloads"
abbr dnls="docker network ls"
abbr dot="git --git-dir ~/.dotfiles/ --work-tree=\$HOME"
abbr dota="git --git-dir ~/.dotfiles/ --work-tree=\$HOME add"
abbr dotc="git --git-dir ~/.dotfiles/ --work-tree=\$HOME commit -m"
abbr dotl="git --git-dir ~/.dotfiles/ --work-tree=\$HOME log --all --decorate --oneline --graph"
abbr dotrm="git --git-dir ~/.dotfiles/ --work-tree=\$HOME rm --cached -r"
abbr dots="git --git-dir ~/.dotfiles/ --work-tree=\$HOME status"
abbr dotu="git --git-dir ~/.dotfiles/ --work-tree=\$HOME add -u && git  --git-dir ~/.dotfiles/ --work-tree=\$HOME status"
abbr dps="docker ps -a"
abbr dsa="docker stop (docker ps -q)"
abbr dt="cd ~/Desktop"
abbr dv="cd ~/Developer"
abbr dvf="cd ~/Developer/flutter"
abbr dvg="cd ~/Developer/go"
abbr fr="flutter run"
abbr gas="git add -A && git status"
abbr gc="git commit -m"
abbr gd="git diff HEAD"
abbr gl="git log --all --decorate --oneline --graph"
abbr gopg="code ~/Developer/Go/playground"
abbr gp="git push"
abbr gs="git status"
abbr history="history 1"
abbr hm="cd ~/"
abbr hs="history 1 | grep"
abbr kc="kubectl"
abbr math="zcalc -e"
abbr myip="curl -s icanhazip.com || echo \"N/A\""
abbr nt="cd ~/Documents/Notes"
abbr of="open ."
abbr rl="exec zsh"
abbr sc="systemctl"
abbr zc="cd ~/.zsh_custom"
abbr zcd="cd \$HOME/.zsh_custom"
abbr zcode="code ~/.zsh_custom"
abbr zrc="nano ~/.zshrc"
