abbr 1="cd ~1"
abbr 2="cd ~2"
abbr 3="cd ~3"
abbr 4="cd ~4"
abbr 5="cd ~5"
abbr 6="cd ~6"
abbr 7="cd ~7"
abbr 8="cd ~8"
abbr 9="cd ~9"
abbr aled="nano ~/.zsh_custom/aliases.zsh"
abbr bpg="nano \$HOME/Developer/Misc/Shell/test.sh"
abbr c="code ."
abbr cdm="cd ~/Developer/pillar/src/clients/mobile/adalpha_investor_app"
abbr cdp="cd ~/Developer/pillar"
abbr cdpt="cd ~/Developer/pillar-temp"
abbr cl="clear"
abbr cwd="echo -n \$(pwd) | xclip -selection clipboard"
abbr d="dirs -v | head -10"
abbr db="docker build ."
abbr dcb="docker-compose build"
abbr dcd="docker-compose down"
abbr dcdb="docker-compose --profile dev build"
abbr dcdd="docker-compose --profile dev down"
abbr dcdu="docker-compose --profile dev up -d"
abbr dcls="docker container ls"
abbr dcp="docker container prune"
abbr dcrb="docker-compose down && docker-compose build && docker-compose up -d"
abbr dcu="docker-compose up -d"
abbr de="docker exec -it"
abbr diffc="code ~/Developer/diff"
abbr dils="docker image ls"
abbr dip="docker image prune -a"
abbr dl="cd ~/Downloads"
abbr dnls="docker network ls"
abbr dot="git --git-dir ~/.dotfiles/ --work-tree=\$HOME"
abbr dota="git --git-dir ~/.dotfiles/ --work-tree=\$HOME add"
abbr dotc="git --git-dir ~/.dotfiles/ --work-tree=\$HOME commit -m"
abbr dotl="git --git-dir ~/.dotfiles/ --work-tree=\$HOME log --all --decorate --oneline --graph"
abbr dotrm="git --git-dir ~/.dotfiles/ --work-tree=\$HOME rm --cached -r"
abbr dots="git --git-dir ~/.dotfiles/ --work-tree=\$HOME status"
abbr dotu="git --git-dir ~/.dotfiles/ --work-tree=\$HOME add -u && git  --git-dir ~/.dotfiles/ --work-tree=\$HOME status"
abbr dps="docker ps -a"
abbr dre="docker run -it"
abbr ds="docker container ls | grep"
abbr dsa="docker stop (docker ps -q)"
abbr dt="cd ~/Desktop"
abbr dv="cd ~/Developer"
abbr dvf="cd ~/Developer/flutter"
abbr dvg="cd ~/Developer/go"
abbr epl="eval \`pillar login"
abbr eptn="eval \`pillar tools nomad\`"
abbr eptv="eval \`pillar tools vault\`"
abbr fk="sudo \$(fc -ln -1)"
abbr fndb="/home/ted/fix-file-is-not-a-database.sh"
abbr fr="flutter run"
abbr gas="git add -A && git status"
abbr gaw="git add -A && git commit -m \"WIP\""
abbr gbr="git reflog | egrep -io \"moving from ([^[:space:]]+)\" | awk '{ print \$3 }' | awk '{ if (seen[\$0] == 0) { print; seen[\$0]++; } }' | egrep -v '^[a-f0-9]{40}$' | head -n10"
abbr gc="git commit -m"
abbr gca="git commit --amend --no-edit"
abbr gcf="git commit --fixup"
abbr gcw="git commit -m 'WIP'"
abbr gd="git diff HEAD"
abbr gf="git fetch"
abbr ggg="pushd ~/Developer/pillar; cd src; go generate -tags=generate ./...; popd"
abbr gl="git log --decorate --oneline --graph"
abbr gla="git log --all --decorate --oneline --graph"
abbr gogen="cd src/; go generate -tags=generate ./...; cd -"
abbr gopg="code ~/Developer/misc/playground"
abbr gp="git diff HEAD > ~/Desktop/tmp.patch && open ~/Desktop"
abbr gpf="git push -f origin HEAD"
abbr grh="git reset HEAD~"
abbr grhh="git reset --hard HEAD"
abbr gri="git rebase -i --autosquash"
abbr gs="git status"
abbr gsad="git stash apply stash^{/drawio}"
abbr gsd="git stash push -u *.dio -m \"drawio\""
abbr gsl="git stash list"
abbr gsw="git switch"
abbr gwls="git worktree list"
abbr history="history 1"
abbr hm="cd ~/"
abbr hs="history 1 | grep"
abbr kc="kubectl"
abbr makeapp="make -f makefile.app"
abbr math="zcalc -e"
abbr mjg="make -j4 generate --output-sync=target"
abbr mjs="make -j4 sql"
abbr nrc="nano \$HOME/.nanorc"
abbr nt="cd ~/Documents/notes"
abbr of="open ."
abbr pbcopy="xclip -selection clipboard"
abbr pbpaste="xclip -selection clipboard -o"
abbr pcl="pillar clients lint"
abbr ped="pillar events decode"
abbr pg="ping 8.8.8.8"
abbr pillaradv="xdg-open https://local.pillar/adviser"
abbr pillarops="xdg-open https://local.pillar/operations"
abbr pso="opera \"\$(pillar seed ops -v --email edward.lucas-rowe+local@adalpha.io --not-role users-admin | tail -n 1)\" &"
abbr pso2="opera --incognito --new-window \"\$(pillar seed ops -v --email edward.lucas-rowe+local2@adalpha.io --not-role users-admin | tail -n 1)\" &"
abbr ptg="pillar tools grafana"
abbr ptj="pillar tools jaeger"
abbr ptm="pillar tools messages"
abbr ptmc="curl -s http://smocks.service.pillar:9535/messages | jq '.[0].body' | grep -oP '(\d+)' | xclip -selection clipboard"
abbr ptn="pillar tools nomad"
abbr pts="pillar tools sql"
abbr ptsc="eval \`pillar tools vault\` && eval \`pillar tools sql\` && connection_string=\"postgresql://\$PGUSER:\$PGPASSWORD@\$PGHOST:\$PGPORT/\$PGDATABASE?sslmode=disable&application_name=pillar-cli\" && jq \".database.\\"1684224621164\\".connectionUrl = \\"\$connection_string\\"\" /home/ted/.config/Code/User/globalStorage/cweijan.vscode-postgresql-client2/config.json | sponge /home/ted/.config/Code/User/globalStorage/cweijan.vscode-postgresql-client2/config.json"
abbr ptv="pillar tools vault"
abbr pv="pillar vm"
abbr pvk="pillar vm reset"
abbr pvm="pillar vm make"
abbr pvr="sudo echo \"Starting platform\" && make pillar && eval \`pillar login local.pillar -k\` && pillar run && paplay /usr/share/sounds/freedesktop/stereo/complete.oga || paplay /usr/share/sounds/freedesktop/stereo/service-logout.oga"
abbr pvrer="sudo echo \"Resetting platform\" && pillar destroy && echo \"Starting platform\" && make pillar && eval \`pillar login local.pillar -k\` && pillar run && paplay /usr/share/sounds/freedesktop/stereo/complete.oga || paplay /usr/share/sounds/freedesktop/stereo/service-logout.oga"
abbr rcp="marktext ~/Documents/recipes/ &"
abbr rf="find . -type f -exec stat --format=\"%Y %n\" {} \; | sort -nr | head"
abbr rl="exec zsh"
abbr sc="systemctl"
abbr svm="scp /home/ted/Developer/misc/vm-aliases/.bash_aliases ubuntu@local.pillar:~/.bash_aliases && ssh -t ubuntu@local.pillar 'cd ~/pillar ; bash --login'"
abbr t="tmux"
abbr ta="tmux attach"
abbr tls="tmux ls"
abbr trc="nano \$HOME/.tmux.conf"
abbr zc="cd ~/.zsh_custom"
abbr zcd="cd \$HOME/.zsh_custom"
abbr zcode="code ~/.zsh_custom"
abbr zrc="nano ~/.zshrc"
