#! /bin/bash

zsh_custom_dir=$(dirname $0)
cd $zsh_custom_dir

# check the plugins, cloning if necessary
[[ -e zsh-abbr ]] && echo 'zsh-abbr already installed' || git clone --depth=1 https://github.com/olets/zsh-abbr.git
[[ -e zsh-autosuggestions ]] && echo 'zsh-autosuggestions already installed' || git clone --depth=1 https://github.com/zsh-users/zsh-autosuggestions.git
[[ -e zsh-history-substring-search ]] && echo 'zsh-history-substring-search already installed' || git clone --depth=1 https://github.com/zsh-users/zsh-history-substring-search.git
[[ -e zsh-syntax-highlighting ]] && echo 'zsh-syntax-highlighting already installed' || git clone --depth=1 https://github.com/zsh-users/zsh-syntax-highlighting.git

# if linux, then edit the .nanorc to point to the correct nano syntax highlighting path
if [[ $OSTYPE == linux* ]]; then
    sed -i 's/\/usr\/local/\/usr/g' "$HOME/.nanorc"
fi    