#!/usr/bin/env bash
# Run as root

# install useful tools
apt update
apt install wget git curl trash-cli -y

# install lf for linux
wget https://github.com/gokcehan/lf/releases/download/r6/lf-linux-amd64.tar.gz \
	-O lf-linux-amd64.tar.gz
tar xvf lf-linux-amd64.tar.gz
chmod +x lf
mv lf /usr/local/bin
rm lf-linux-amd64.tar.gz

# install ctop for containers
echo "deb http://packages.azlux.fr/debian/ buster main" | tee /etc/apt/sources.list.d/azlux.list
wget -qO - https://azlux.fr/repo.gpg.key | apt-key add -
apt update
apt install docker-ctop -y

# install and update tldr
apt install tldr
tldr -u

# install ufw for firewall management
apt install ufw

# install fish for linux
apt install fish

chsh -s $(which fish) $SUDO_USER

# install omf for showing git repo status'
curl https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install | fish